//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.Texts.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change profile.
        /// </summary>
        internal static string EditProfileButton {
            get {
                return ResourceManager.GetString("EditProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the verification code to log in.
        /// </summary>
        internal static string EnterCodeDescription {
            get {
                return ResourceManager.GetString("EnterCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can request a new code after:.
        /// </summary>
        internal static string EnterCodeTimerText {
            get {
                return ResourceManager.GetString("EnterCodeTimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time code.
        /// </summary>
        internal static string EnterCodeTitle {
            get {
                return ResourceManager.GetString("EnterCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number to which the verification code will be sent..
        /// </summary>
        internal static string EnterPhoneDescription {
            get {
                return ResourceManager.GetString("EnterPhoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        internal static string EnterPhoneErrorText {
            get {
                return ResourceManager.GetString("EnterPhoneErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string EnterPhoneTitle {
            get {
                return ResourceManager.GetString("EnterPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My adresses.
        /// </summary>
        internal static string MyAdresses {
            get {
                return ResourceManager.GetString("MyAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment methods.
        /// </summary>
        internal static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyAgreement {
            get {
                return ResourceManager.GetString("PrivacyPolicyAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code.
        /// </summary>
        internal static string PromoCode {
            get {
                return ResourceManager.GetString("PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request new code.
        /// </summary>
        internal static string RequestNewCode {
            get {
                return ResourceManager.GetString("RequestNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust contact.
        /// </summary>
        internal static string TrustContact {
            get {
                return ResourceManager.GetString("TrustContact", resourceCulture);
            }
        }
    }
}
